import Foundation

// Make Me a Drink: more liqueur, amaro and aperitivo drinks, so the Liqueur chip has 20+ to surprise with.
extension CocktailLibrary {
    static let moreLiqueur: [Cocktail] = [
        Cocktail("americano", "Americano", base: .liqueur, style: .highball, strength: .light,
                 blurb: "Campari, sweet vermouth and soda: the Negroni's lighter ancestor.",
                 ingredients: [I("1½", "Campari"), I("1½", "sweet vermouth"), I("", "club soda to top")],
                 steps: build, glass: "Rocks or highball glass", garnish: "Orange slice",
                 orderTip: "A low-proof aperitivo; great before dinner."),
        Cocktail("campari-soda", "Campari Soda", base: .liqueur, style: .highball, strength: .light,
                 blurb: "Bitter Campari and cold soda, simple and bracing.",
                 ingredients: [I("2", "Campari"), I("4", "club soda")],
                 steps: build, glass: "Highball glass", garnish: "Orange slice",
                 orderTip: "The easiest way to see if you like bitter Italian aperitivi."),
        Cocktail("garibaldi", "Garibaldi", base: .liqueur, style: .highball, strength: .light,
                 blurb: "Campari and fluffy, freshly juiced orange.",
                 ingredients: [I("1½", "Campari"), I("4", "fresh orange juice, blended or shaken until frothy")],
                 steps: ["Fill the glass with ice and add the Campari.", "Top with the fluffy orange juice and stir gently."],
                 glass: "Highball glass", garnish: "Orange wedge",
                 orderTip: "Best where they juice oranges to order."),
        Cocktail("pimms-cup", "Pimm's Cup", aliases: ["pimm's", "pimms cup", "pimm's no. 1 cup"], base: .liqueur, style: .highball, strength: .light,
                 blurb: "Pimm's, lemonade and a garden of fruit and cucumber.",
                 ingredients: [I("2", "Pimm's No. 1"), I("4", "British-style lemonade (or ginger ale)"), I("", "cucumber, strawberry, orange and mint")],
                 steps: ["Fill the glass with ice and the fruit.", "Add Pimm's and top with lemonade.", "Stir gently."],
                 glass: "Highball glass or pitcher", garnish: "Cucumber, strawberry and mint",
                 orderTip: "The drink of Wimbledon; order a jug for the table."),
        Cocktail("hugo-spritz", "Hugo Spritz", aliases: ["hugo"], base: .liqueur, style: .spritz, strength: .light,
                 blurb: "Elderflower, prosecco, mint and lime: floral and fresh.",
                 ingredients: [I("¾", "elderflower liqueur (St-Germain)"), I("4", "prosecco"), I("1", "club soda"), I("6", "mint leaves")],
                 steps: ["Gently press the mint in a wine glass.", "Add ice, elderflower and prosecco.", "Top with soda and stir once."],
                 glass: "Wine glass", garnish: "Mint sprig and lime wheel",
                 orderTip: "A sweeter, more floral alternative to an Aperol Spritz."),
        Cocktail("limoncello-spritz", "Limoncello Spritz", base: .liqueur, style: .spritz, strength: .light,
                 blurb: "Limoncello, prosecco and soda, like sparkling lemonade.",
                 ingredients: [I("2", "limoncello"), I("3", "prosecco"), I("1", "club soda")],
                 steps: ["Fill a wine glass with ice.", "Add prosecco, then limoncello, then soda.", "Stir once."],
                 glass: "Wine glass", garnish: "Lemon wheel and mint",
                 orderTip: "Sunny and sweet-tart; a summer patio favorite."),
        Cocktail("st-germain-cocktail", "St-Germain Cocktail", aliases: ["elderflower spritz", "st germain spritz"], base: .liqueur, style: .spritz, strength: .light,
                 blurb: "Elderflower liqueur, sparkling wine and soda.",
                 ingredients: [I("1½", "St-Germain"), I("2", "dry sparkling wine"), I("2", "club soda")],
                 steps: ["Fill a Collins glass with ice.", "Add St-Germain and sparkling wine.", "Top with soda and stir gently."],
                 glass: "Collins glass", garnish: "Lemon twist",
                 orderTip: "Floral and light, with no herbs to muddle."),
        Cocktail("midori-sour", "Midori Sour", base: .liqueur, style: .sour, strength: .light,
                 blurb: "Bright green melon liqueur with lemon and lime.",
                 ingredients: [I("1½", "Midori"), I("½", "fresh lemon juice"), I("½", "fresh lime juice"), I("", "splash of club soda")],
                 steps: ["Shake the Midori and juices with ice.", "Strain over fresh ice.", "Top with a splash of soda."],
                 glass: "Rocks or Collins glass", garnish: "Lemon wheel and cherry",
                 orderTip: "Ask for fresh citrus rather than sour mix."),
        Cocktail("mudslide", "Mudslide", base: .liqueur, style: .creamy, strength: .medium,
                 blurb: "Irish cream, coffee liqueur and vodka: an adult milkshake.",
                 ingredients: [I("1", "Irish cream"), I("1", "coffee liqueur"), I("1", "vodka"), I("1", "heavy cream (optional)")],
                 steps: ["Shake everything with ice.", "Strain over fresh ice (or blend with ice and a scoop of vanilla ice cream)."],
                 glass: "Rocks or hurricane glass", garnish: "Chocolate syrup drizzle",
                 orderTip: "Ask for it frozen if they have a blender."),
        Cocktail("pink-squirrel", "Pink Squirrel", base: .liqueur, style: .creamy, strength: .light,
                 blurb: "Almond crème de noyaux, cacao and cream, blushing pink.",
                 ingredients: [I("¾", "crème de noyaux"), I("¾", "white crème de cacao"), I("1½", "heavy cream")],
                 steps: shakeSour, glass: "Coupe", garnish: "Grated nutmeg",
                 orderTip: "A retro Wisconsin dessert drink, often blended with ice cream."),
        Cocktail("chartreuse-swizzle", "Chartreuse Swizzle", base: .liqueur, style: .tiki, strength: .strong,
                 blurb: "Green Chartreuse, pineapple, lime and falernum over crushed ice.",
                 ingredients: [I("1¼", "green Chartreuse"), I("1", "pineapple juice"), I("¾", "fresh lime juice"), I("½", "falernum")],
                 steps: ["Add everything to the glass and fill with crushed ice.", "Swizzle until the glass frosts.", "Top with more crushed ice."],
                 glass: "Collins glass", garnish: "Mint sprig and grated nutmeg",
                 orderTip: "Herbal and tropical; Chartreuse is strong, so sip slowly."),
        Cocktail("fernet-and-coke", "Fernet & Coke", aliases: ["fernet con coca", "fernet and coke"], base: .liqueur, style: .highball, strength: .medium,
                 blurb: "Bitter, minty Fernet-Branca with cola, Argentina's national highball.",
                 ingredients: [I("2", "Fernet-Branca"), I("5", "cola")],
                 steps: build, glass: "Highball glass", garnish: "None",
                 orderTip: "Pour the cola slowly; it foams up fast."),
        Cocktail("fuzzy-navel", "Fuzzy Navel", base: .liqueur, style: .highball, strength: .light,
                 blurb: "Peach schnapps and orange juice. Sweet and simple.",
                 ingredients: [I("2", "peach schnapps"), I("4", "orange juice")],
                 steps: build, glass: "Highball glass", garnish: "Orange slice",
                 orderTip: "Add a splash of vodka and it becomes a Hairy Navel."),
        Cocktail("alabama-slammer", "Alabama Slammer", base: .liqueur, style: .highball, strength: .medium,
                 blurb: "Southern Comfort, amaretto, sloe gin and orange juice.",
                 ingredients: [I("¾", "Southern Comfort"), I("¾", "amaretto"), I("¾", "sloe gin"), I("2", "orange juice")],
                 steps: ["Shake everything with ice.", "Strain into an ice-filled glass."],
                 glass: "Highball glass", garnish: "Orange slice and cherry",
                 orderTip: "Fruity and nostalgic; also served as a shot."),
        Cocktail("b-52", "B-52", aliases: ["b52"], base: .liqueur, style: .shot, strength: .medium,
                 blurb: "Coffee liqueur, Irish cream and Grand Marnier in three neat layers.",
                 ingredients: [I("½", "coffee liqueur"), I("½", "Irish cream"), I("½", "Grand Marnier")],
                 steps: ["Pour the coffee liqueur into a shot glass.", "Layer the Irish cream over the back of a spoon.", "Layer the Grand Marnier on top."],
                 glass: "Shot glass", garnish: "None",
                 orderTip: "A classic layered shot; some bars flame the top."),
        Cocktail("baby-guinness", "Baby Guinness", base: .liqueur, style: .shot, strength: .light,
                 blurb: "Coffee liqueur topped with Irish cream, a tiny pint lookalike.",
                 ingredients: [I("1", "coffee liqueur"), I("¼", "Irish cream")],
                 steps: ["Pour the coffee liqueur into a shot glass.", "Float the Irish cream on top over the back of a spoon."],
                 glass: "Shot glass", garnish: "None",
                 orderTip: "Sweet and dessert-like; a fun round for an Irish pub."),
        Cocktail("jagerbomb", "Jägerbomb", aliases: ["jagerbomb", "jager bomb"], base: .liqueur, style: .shot, strength: .medium,
                 blurb: "A shot of Jägermeister dropped into energy drink.",
                 ingredients: [I("1½", "Jägermeister"), I("4", "energy drink")],
                 steps: ["Pour the energy drink into a pint or rocks glass.", "Fill a shot glass with Jägermeister.", "Drop the shot in and drink right away."],
                 glass: "Shot glass and rocks glass", garnish: "None",
                 orderTip: "A party round, not a sipper; one is usually plenty."),
    ]
}
