import Foundation

// Make Me a Drink: more zero-proof drinks and mocktails, so the Zero-proof chip has 20+ to surprise with.
extension CocktailLibrary {
    static let moreZeroProof: [Cocktail] = [
        Cocktail("virgin-mary", "Virgin Mary", aliases: ["bloody mary mocktail"], base: .zeroProof, style: .highball, strength: .light,
                 blurb: "All the savory, spicy tomato of a Bloody Mary, no vodka.",
                 ingredients: [I("6", "tomato juice"), I("½", "fresh lemon juice"), I("", "Worcestershire, hot sauce, celery salt, horseradish and pepper to taste")],
                 steps: ["Add everything to a glass with ice.", "Roll between two tins (or stir) to mix.", "Garnish generously."],
                 glass: "Pint or highball glass", garnish: "Celery stalk, lemon and olives",
                 orderTip: "Tell them how spicy you like it."),
        Cocktail("virgin-pina-colada", "Virgin Piña Colada", aliases: ["virgin pina colada", "piña colada mocktail"], base: .zeroProof, style: .frozen, strength: .light,
                 blurb: "Pineapple and coconut blended with ice.",
                 ingredients: [I("4", "pineapple juice"), I("2", "cream of coconut"), I("½", "fresh lime juice")],
                 steps: ["Blend everything with a cup of ice until smooth.", "Pour into the glass."],
                 glass: "Hurricane glass", garnish: "Pineapple wedge and cherry",
                 orderTip: "Any bar with a blender can make it."),
        Cocktail("virgin-strawberry-daiquiri", "Virgin Strawberry Daiquiri", aliases: ["strawberry daiquiri mocktail"], base: .zeroProof, style: .frozen, strength: .light,
                 blurb: "Strawberries, lime and sugar blended into a frosty slush.",
                 ingredients: [I("1 cup", "strawberries (fresh or frozen)"), I("1", "fresh lime juice"), I("¾", "simple syrup")],
                 steps: ["Blend everything with a cup of ice until smooth.", "Pour into the glass."],
                 glass: "Hurricane or coupe glass", garnish: "Strawberry",
                 orderTip: "A kid-friendly favorite on any resort menu."),
        Cocktail("roy-rogers", "Roy Rogers", base: .zeroProof, style: .highball, strength: .light,
                 blurb: "Cola with a splash of grenadine and a cherry.",
                 ingredients: [I("6", "cola"), I("½", "grenadine")],
                 steps: build, glass: "Highball glass", garnish: "Maraschino cherries",
                 orderTip: "The Shirley Temple's cola-based partner."),
        Cocktail("cinderella", "Cinderella", base: .zeroProof, style: .fizzy, strength: .light,
                 blurb: "Orange, pineapple and lemon with grenadine and a fizzy top.",
                 ingredients: [I("1½", "orange juice"), I("1½", "pineapple juice"), I("½", "fresh lemon juice"), I("¼", "grenadine"), I("2", "club soda")],
                 steps: ["Shake the juices and grenadine with ice.", "Strain into an ice-filled glass.", "Top with soda."],
                 glass: "Highball glass", garnish: "Orange slice and cherry",
                 orderTip: "Fruity and pretty; a classic party mocktail."),
        Cocktail("lime-rickey", "Lime Rickey", base: .zeroProof, style: .fizzy, strength: .light,
                 blurb: "Fresh lime, sugar and seltzer, a soda-fountain classic.",
                 ingredients: [I("1", "fresh lime juice"), I("¾", "simple syrup"), I("5", "seltzer")],
                 steps: build, glass: "Highball glass", garnish: "Lime wedge",
                 orderTip: "Add a splash of raspberry syrup for the Boston-style version."),
        Cocktail("cherry-limeade", "Cherry Limeade", base: .zeroProof, style: .fizzy, strength: .light,
                 blurb: "Lemon-lime soda, fresh lime and cherry syrup.",
                 ingredients: [I("6", "lemon-lime soda"), I("¾", "fresh lime juice"), I("½", "cherry syrup or grenadine")],
                 steps: build, glass: "Highball glass", garnish: "Lime wedges and cherries",
                 orderTip: "A drive-in favorite; ask for extra lime if you like it tart."),
        Cocktail("egg-cream", "Egg Cream", base: .zeroProof, style: .creamy, strength: .light,
                 blurb: "Chocolate syrup, cold milk and seltzer: a frothy New York classic with no egg or cream.",
                 ingredients: [I("1", "chocolate syrup"), I("2", "cold whole milk"), I("4", "cold seltzer")],
                 steps: ["Add the syrup and milk to a tall glass.", "Pour in the seltzer while stirring briskly to build a foamy head.", "Stir the syrup up from the bottom and drink right away."],
                 glass: "Soda fountain glass", garnish: "None",
                 orderTip: "Fox's U-Bet chocolate syrup is the traditional choice."),
        Cocktail("lavender-lemonade", "Lavender Lemonade", base: .zeroProof, style: .sour, strength: .light,
                 blurb: "Fresh lemonade with a gentle floral lavender note.",
                 ingredients: [I("1½", "fresh lemon juice"), I("1", "lavender syrup"), I("5", "cold water")],
                 steps: ["Stir the lemon juice and lavender syrup together.", "Add water and ice and stir again."],
                 glass: "Collins glass", garnish: "Lemon wheel and lavender sprig",
                 orderTip: "Swap the water for sparkling water for a fizzy version."),
        Cocktail("watermelon-agua-fresca", "Watermelon Agua Fresca", aliases: ["agua fresca", "agua de sandía"], base: .zeroProof, style: .highball, strength: .light,
                 blurb: "Fresh watermelon blended with water, lime and a little sugar.",
                 ingredients: [I("2 cups", "watermelon chunks"), I("4", "cold water"), I("½", "fresh lime juice"), I("1 tsp", "sugar (to taste)")],
                 steps: ["Blend the watermelon and water until smooth.", "Strain, then stir in lime and sugar.", "Serve over ice."],
                 glass: "Tall glass", garnish: "Lime wheel and mint",
                 orderTip: "Taquerías often have a few flavors on tap; ask what's fresh."),
        Cocktail("horchata", "Horchata", base: .zeroProof, style: .creamy, strength: .light,
                 blurb: "Mexican rice and cinnamon drink, sweet and milky.",
                 ingredients: [I("½ cup", "long-grain white rice"), I("1", "cinnamon stick"), I("3 cups", "water"), I("1 cup", "milk"), I("⅓ cup", "sugar")],
                 steps: ["Soak the rice and cinnamon in the water overnight.", "Blend until smooth and strain well.", "Stir in milk and sugar and serve over ice."],
                 glass: "Tall glass", garnish: "Ground cinnamon",
                 orderTip: "Great with spicy tacos; it cools the heat."),
        Cocktail("hot-apple-cider", "Hot Apple Cider", aliases: ["mulled cider", "hot cider"], base: .zeroProof, style: .hot, strength: .light,
                 blurb: "Apple cider simmered with cinnamon, cloves and orange.",
                 ingredients: [I("8", "unfiltered apple cider"), I("1", "cinnamon stick"), I("3", "whole cloves"), I("1", "orange slice")],
                 steps: ["Warm everything in a pot over low heat for 10 minutes.", "Strain into a mug."],
                 glass: "Mug", garnish: "Cinnamon stick and orange slice",
                 orderTip: "A cozy fall pick; make a big pot for a crowd."),
        Cocktail("espresso-tonic", "Espresso Tonic", base: .zeroProof, style: .highball, strength: .light,
                 blurb: "A shot of espresso floated over cold tonic: bitter, bright and fizzy.",
                 ingredients: [I("4", "tonic water"), I("2", "fresh espresso")],
                 steps: ["Fill the glass with ice and tonic.", "Slowly pour the espresso over the top so it layers."],
                 glass: "Highball glass", garnish: "Orange peel",
                 orderTip: "Many specialty coffee shops have it off-menu; just ask."),
        Cocktail("mango-lassi", "Mango Lassi", base: .zeroProof, style: .creamy, strength: .light,
                 blurb: "Mango, yogurt and a pinch of cardamom blended smooth.",
                 ingredients: [I("4", "mango pulp"), I("3", "plain yogurt"), I("2", "milk"), I("1 tsp", "sugar"), I("", "pinch of ground cardamom")],
                 steps: ["Blend everything with a few ice cubes until smooth.", "Pour into a chilled glass."],
                 glass: "Tall glass", garnish: "Pinch of cardamom or pistachios",
                 orderTip: "The perfect partner for a spicy curry."),
        Cocktail("thai-iced-tea", "Thai Iced Tea", aliases: ["cha yen"], base: .zeroProof, style: .creamy, strength: .light,
                 blurb: "Strong spiced black tea, sweetened and swirled with milk over ice.",
                 ingredients: [I("6", "strong brewed Thai tea, cooled"), I("1", "sweetened condensed milk"), I("1", "evaporated milk or half-and-half")],
                 steps: ["Stir the condensed milk into the tea.", "Pour over a glass full of ice.", "Float the evaporated milk on top."],
                 glass: "Tall glass", garnish: "None",
                 orderTip: "Ask for less sweet if you find it sugary."),
    ]
}
