import Foundation

// Make Me a Drink: more whiskey drinks, so the Whiskey chip has 20+ to surprise with.
extension CocktailLibrary {
    static let moreWhiskey: [Cocktail] = [
        Cocktail("rob-roy", "Rob Roy", base: .whiskey, style: .stirred, strength: .strong,
                 blurb: "A Manhattan made with Scotch: smooth, malty and rich.",
                 ingredients: [I("2", "blended Scotch"), I("1", "sweet vermouth"), I("2 dashes", "Angostura bitters")],
                 steps: stir, glass: "Coupe", garnish: "Brandied cherry",
                 orderTip: "Ask for it \"perfect\" for half sweet, half dry vermouth."),
        Cocktail("rusty-nail", "Rusty Nail", base: .whiskey, style: .stirred, strength: .strong,
                 blurb: "Scotch and honeyed Drambuie over ice.",
                 ingredients: [I("1½", "blended Scotch"), I("¾", "Drambuie")],
                 steps: ["Fill the glass with ice.", "Add the Scotch and Drambuie.", "Stir until chilled."],
                 glass: "Rocks glass", garnish: "Lemon twist",
                 orderTip: "A cozy two-ingredient nightcap."),
        Cocktail("hot-toddy", "Hot Toddy", base: .whiskey, style: .hot, strength: .light,
                 blurb: "Whiskey, honey, lemon and hot water. A warm hug in a mug.",
                 ingredients: [I("1½", "whiskey"), I("½", "honey"), I("½", "fresh lemon juice"), I("4", "hot water")],
                 steps: ["Warm the mug with hot water, then empty it.", "Stir the honey into the hot water until it dissolves.", "Add the whiskey and lemon and stir."],
                 glass: "Mug", garnish: "Lemon wheel and cinnamon stick",
                 orderTip: "The classic for a cold night or a scratchy throat."),
        Cocktail("whiskey-smash", "Whiskey Smash", base: .whiskey, style: .sour, strength: .medium,
                 blurb: "Bourbon, muddled lemon and mint over crushed ice.",
                 ingredients: [I("2", "bourbon"), I("¾", "simple syrup"), I("3", "lemon wedges"), I("8", "mint leaves")],
                 steps: ["Muddle the lemon wedges with the syrup.", "Add the mint, bourbon and ice and shake.", "Double-strain over crushed ice."],
                 glass: "Rocks glass", garnish: "Mint sprig",
                 orderTip: "Like a julep crossed with a whiskey sour."),
        Cocktail("blood-and-sand", "Blood and Sand", base: .whiskey, style: .sour, strength: .medium,
                 blurb: "Equal parts Scotch, cherry liqueur, sweet vermouth and orange juice.",
                 ingredients: [I("¾", "blended Scotch"), I("¾", "cherry liqueur"), I("¾", "sweet vermouth"), I("¾", "fresh orange juice")],
                 steps: shakeSour, glass: "Coupe", garnish: "Orange peel",
                 orderTip: "The Scotch cocktail for people who think they don't like Scotch."),
        Cocktail("ward-eight", "Ward Eight", base: .whiskey, style: .sour, strength: .medium,
                 blurb: "Boston's rye sour with orange and a splash of grenadine.",
                 ingredients: [I("2", "rye whiskey"), I("½", "fresh lemon juice"), I("½", "fresh orange juice"), I("1 tsp", "grenadine")],
                 steps: shakeSour, glass: "Coupe", garnish: "Cherry",
                 orderTip: "A rosy whiskey sour; ask for real pomegranate grenadine."),
        Cocktail("kentucky-mule", "Kentucky Mule", aliases: ["bourbon mule"], base: .whiskey, style: .highball, strength: .light,
                 blurb: "Bourbon, lime and spicy ginger beer.",
                 ingredients: [I("2", "bourbon"), I("½", "fresh lime juice"), I("4", "ginger beer")],
                 steps: build, glass: "Copper mug", garnish: "Lime wedge and mint",
                 orderTip: "Any bar with a Moscow Mule can make it with bourbon."),
        Cocktail("boilermaker", "Boilermaker", base: .whiskey, style: .shot, strength: .medium,
                 blurb: "A shot of whiskey with a cold beer.",
                 ingredients: [I("1½", "whiskey"), I("12", "cold lager")],
                 steps: ["Pour the whiskey into a shot glass.", "Pour the beer into a pint glass.", "Shoot the whiskey and chase it with the beer, or drop it in."],
                 glass: "Shot glass and pint glass", garnish: "None",
                 orderTip: "Many bars have a cheap \"shot and a beer\" special."),
    ]
}
