import Foundation

// Make Me a Drink: more gin drinks, so the Gin chip has 20+ to surprise with.
extension CocktailLibrary {
    static let moreGin: [Cocktail] = [
        Cocktail("bramble", "Bramble", base: .gin, style: .sour, strength: .medium,
                 blurb: "Gin and lemon over crushed ice, bled with blackberry liqueur.",
                 ingredients: [I("2", "gin"), I("1", "fresh lemon juice"), I("½", "simple syrup"), I("½", "crème de mûre (blackberry liqueur)")],
                 steps: ["Shake the gin, lemon and syrup with ice.", "Strain into a glass packed with crushed ice.", "Drizzle the crème de mûre over the top."],
                 glass: "Rocks glass", garnish: "Blackberry and lemon slice",
                 orderTip: "A modern London classic; great if you like berries."),
        Cocktail("corpse-reviver-2", "Corpse Reviver No. 2", aliases: ["corpse reviver"], base: .gin, style: .sour, strength: .strong,
                 blurb: "Equal parts gin, Cointreau, Lillet and lemon with an absinthe rinse.",
                 ingredients: [I("¾", "gin"), I("¾", "Cointreau"), I("¾", "Lillet Blanc"), I("¾", "fresh lemon juice"), I("", "absinthe to rinse")],
                 steps: ["Rinse a chilled coupe with absinthe and discard.", "Shake the rest with ice.", "Strain into the glass."],
                 glass: "Coupe", garnish: "Orange twist",
                 orderTip: "Bright and deceptively strong; one is plenty."),
        Cocktail("gin-fizz", "Gin Fizz", base: .gin, style: .fizzy, strength: .light,
                 blurb: "Gin, lemon and sugar, shaken and lifted with soda.",
                 ingredients: [I("2", "gin"), I("1", "fresh lemon juice"), I("¾", "simple syrup"), I("1", "egg white (optional)"), I("", "club soda to top")],
                 steps: ["Shake gin, lemon, syrup and egg white without ice, then with ice.", "Strain into a chilled glass with no ice.", "Top with soda."],
                 glass: "Fizz or highball glass", garnish: "Lemon twist",
                 orderTip: "With egg white it's a Silver Fizz: frothier and silkier."),
        Cocktail("ramos-gin-fizz", "Ramos Gin Fizz", base: .gin, style: .creamy, strength: .light,
                 blurb: "New Orleans' frothy gin fizz with cream, citrus and orange flower water.",
                 ingredients: [I("2", "gin"), I("½", "fresh lemon juice"), I("½", "fresh lime juice"), I("¾", "simple syrup"), I("1", "heavy cream"), I("1", "egg white"), I("3 drops", "orange flower water"), I("1", "club soda")],
                 steps: ["Shake everything but the soda without ice for 15 seconds.", "Add ice and shake hard for a full minute.", "Strain into a chilled glass and top slowly with soda so the foam rises."],
                 glass: "Collins glass", garnish: "None",
                 orderTip: "It takes a lot of shaking, so order it when the bar isn't slammed."),
        Cocktail("clover-club", "Clover Club", base: .gin, style: .sour, strength: .medium,
                 blurb: "Gin, raspberry and lemon with a silky pink foam.",
                 ingredients: [I("1½", "gin"), I("½", "raspberry syrup"), I("½", "fresh lemon juice"), I("½", "egg white")],
                 steps: ["Shake everything without ice first.", "Add ice and shake hard.", "Strain into a chilled coupe."],
                 glass: "Coupe", garnish: "Fresh raspberries",
                 orderTip: "A pre-Prohibition classic that's fruity but not too sweet."),
        Cocktail("vesper", "Vesper", aliases: ["vesper martini"], base: .gin, style: .stirred, strength: .strong,
                 blurb: "James Bond's martini: gin, vodka and Lillet Blanc.",
                 ingredients: [I("3", "gin"), I("1", "vodka"), I("½", "Lillet Blanc")],
                 steps: stir, glass: "Martini glass or coupe", garnish: "Long lemon peel",
                 orderTip: "Bond had it shaken; most bartenders stir it."),
        Cocktail("martinez", "Martinez", base: .gin, style: .stirred, strength: .strong,
                 blurb: "The Martini's sweeter ancestor: gin, sweet vermouth and maraschino.",
                 ingredients: [I("1½", "gin (Old Tom if you have it)"), I("1½", "sweet vermouth"), I("1 tsp", "maraschino liqueur"), I("2 dashes", "orange bitters")],
                 steps: stir, glass: "Coupe", garnish: "Orange peel",
                 orderTip: "Like a Manhattan made with gin."),
        Cocktail("singapore-sling", "Singapore Sling", base: .gin, style: .tiki, strength: .medium,
                 blurb: "Gin, cherry, pineapple and lime from Raffles Hotel.",
                 ingredients: [I("1", "gin"), I("½", "cherry liqueur"), I("¼", "Cointreau"), I("¼", "Bénédictine"), I("4", "pineapple juice"), I("½", "fresh lime juice"), I("¼", "grenadine"), I("1 dash", "Angostura bitters")],
                 steps: ["Shake everything with ice.", "Strain into an ice-filled glass."],
                 glass: "Hurricane or highball glass", garnish: "Pineapple slice and cherry",
                 orderTip: "Fruity and tropical, with more going on than it looks."),
        Cocktail("gin-rickey", "Gin Rickey", base: .gin, style: .fizzy, strength: .light,
                 blurb: "Gin, fresh lime and soda. Bone dry and refreshing.",
                 ingredients: [I("2", "gin"), I("½", "fresh lime juice"), I("4", "club soda")],
                 steps: build, glass: "Highball glass", garnish: "Lime wedge",
                 orderTip: "No sugar at all; ask for a splash of syrup if you want it softer."),
        Cocktail("gin-basil-smash", "Gin Basil Smash", aliases: ["gin smash"], base: .gin, style: .sour, strength: .medium,
                 blurb: "Gin, lemon and a handful of fresh basil, bright green and herbal.",
                 ingredients: [I("2", "gin"), I("¾", "fresh lemon juice"), I("½", "simple syrup"), I("10", "basil leaves")],
                 steps: ["Muddle the basil with the lemon and syrup.", "Add gin and ice and shake hard.", "Double-strain over fresh ice."],
                 glass: "Rocks glass", garnish: "Basil sprig",
                 orderTip: "A Hamburg modern classic; perfect in summer."),
    ]
}
