import Foundation

// Make Me a Drink: more mezcal drinks, so the Mezcal chip has 20+ to surprise with.
extension CocktailLibrary {
    static let moreMezcal: [Cocktail] = [
        Cocktail("mezcal-margarita", "Mezcal Margarita", aliases: ["mezcalita", "smoky margarita"], base: .mezcal, style: .sour, strength: .medium,
                 blurb: "The margarita made with mezcal: smoky, tart and salty.",
                 ingredients: [I("2", "mezcal"), I("1", "fresh lime juice"), I("¾", "Cointreau"), I("¼", "agave syrup")],
                 steps: ["Rim the glass with salt or Tajín.", "Shake everything with ice.", "Strain over fresh ice."],
                 glass: "Rocks glass", garnish: "Lime wheel, salt or Tajín rim",
                 orderTip: "Ask for half tequila, half mezcal if you want less smoke."),
        Cocktail("frozen-mezcal-margarita", "Frozen Mezcal Margarita", base: .mezcal, style: .frozen, strength: .medium,
                 blurb: "A slushy margarita with a gentle wisp of smoke.",
                 ingredients: [I("2", "mezcal"), I("¾", "Cointreau"), I("1", "fresh lime juice"), I("½", "agave syrup")],
                 steps: ["Rim the glass with chili salt.", "Blend everything with a cup of ice until smooth.", "Pour into the glass."],
                 glass: "Margarita glass", garnish: "Lime wheel, chili-salt rim",
                 orderTip: "Mango or pineapple frozen versions pair beautifully with the smoke."),
        Cocktail("mezcal-mule", "Mezcal Mule", base: .mezcal, style: .highball, strength: .light,
                 blurb: "Mezcal, lime, passion fruit, cucumber and ginger beer.",
                 ingredients: [I("1½", "mezcal"), I("¾", "fresh lime juice"), I("½", "passion fruit purée"), I("½", "agave syrup"), I("3", "cucumber slices"), I("", "ginger beer to top")],
                 steps: ["Muddle the cucumber in a shaker.", "Add mezcal, lime, purée and agave; shake with ice.", "Strain into an ice-filled glass and top with ginger beer."],
                 glass: "Copper mug or highball", garnish: "Cucumber slice and candied ginger",
                 orderTip: "A smoky spin on the Moscow Mule."),
        Cocktail("mezcal-paloma", "Mezcal Paloma", aliases: ["smoky paloma"], base: .mezcal, style: .fizzy, strength: .light,
                 blurb: "Mezcal, lime and grapefruit soda with a salted rim.",
                 ingredients: [I("2", "mezcal"), I("½", "fresh lime juice"), I("4", "grapefruit soda"), I("", "pinch of salt")],
                 steps: build, glass: "Highball glass with salt rim", garnish: "Grapefruit wedge",
                 orderTip: "Ask for fresh grapefruit juice and soda water if they make it from scratch."),
        Cocktail("division-bell", "Division Bell", base: .mezcal, style: .sour, strength: .medium,
                 blurb: "Mezcal, Aperol, maraschino and lime: smoky, bitter and bright.",
                 ingredients: [I("1", "mezcal"), I("¾", "Aperol"), I("½", "maraschino liqueur"), I("¾", "fresh lime juice")],
                 steps: shakeSour, glass: "Coupe", garnish: "Grapefruit twist",
                 orderTip: "A modern classic from New York's Mayahuel; try it where they love agave."),
        Cocktail("mezcal-old-fashioned", "Mezcal Old Fashioned", base: .mezcal, style: .stirred, strength: .strong,
                 blurb: "All mezcal, a little agave and bitters over one big cube.",
                 ingredients: [I("2", "mezcal"), I("¼", "agave syrup"), I("2 dashes", "Angostura or mole bitters")],
                 steps: ["Stir everything with ice.", "Strain over a big ice cube.", "Express an orange peel over the top."],
                 glass: "Rocks glass", garnish: "Orange peel",
                 orderTip: "Smokier than the Oaxaca Old Fashioned, which is mostly tequila."),
        Cocktail("mezcal-last-word", "Mezcal Last Word", base: .mezcal, style: .sour, strength: .strong,
                 blurb: "Equal parts mezcal, green Chartreuse, maraschino and lime.",
                 ingredients: [I("¾", "mezcal"), I("¾", "green Chartreuse"), I("¾", "maraschino liqueur"), I("¾", "fresh lime juice")],
                 steps: shakeSour, glass: "Coupe", garnish: "None",
                 orderTip: "Herbal and smoky; for Last Word fans who want more depth."),
        Cocktail("mezcal-sour", "Mezcal Sour", base: .mezcal, style: .sour, strength: .medium,
                 blurb: "Mezcal, lime and sugar, silky with egg white.",
                 ingredients: [I("2", "mezcal"), I("¾", "fresh lime juice"), I("¾", "simple syrup"), I("1", "egg white (optional)")],
                 steps: ["Shake everything without ice first if using egg white.", "Add ice and shake hard.", "Strain into the glass."],
                 glass: "Coupe or rocks glass", garnish: "Angostura drops",
                 orderTip: "A gentle way into mezcal: the citrus softens the smoke."),
        Cocktail("tia-mia", "Tia Mia", base: .mezcal, style: .tiki, strength: .strong,
                 blurb: "A Mai Tai split between mezcal and Jamaican rum.",
                 ingredients: [I("1", "mezcal"), I("1", "aged Jamaican rum"), I("¾", "fresh lime juice"), I("½", "orange curaçao"), I("½", "orgeat")],
                 steps: ["Shake with crushed ice.", "Pour everything into the glass.", "Top with more crushed ice."],
                 glass: "Double rocks glass", garnish: "Mint sprig, lime wheel and an orchid",
                 orderTip: "Mai Tai lovers: this one adds smoke and funk."),
        Cocktail("mezcal-manhattan", "Mezcal Manhattan", base: .mezcal, style: .stirred, strength: .strong,
                 blurb: "Mezcal, sweet vermouth and bitters. A smoky Manhattan.",
                 ingredients: [I("2", "mezcal"), I("1", "sweet vermouth"), I("2 dashes", "Angostura bitters")],
                 steps: stir, glass: "Coupe or Nick & Nora", garnish: "Brandied cherry or orange peel",
                 orderTip: "Ask for a rich vermouth like Carpano Antica to balance the smoke."),
        Cocktail("mezcal-espresso-martini", "Mezcal Espresso Martini", base: .mezcal, style: .creamy, strength: .medium,
                 blurb: "Mezcal, coffee liqueur and fresh espresso with a foamy top.",
                 ingredients: [I("1½", "mezcal"), I("1", "fresh espresso"), I("½", "coffee liqueur"), I("¼", "simple syrup")],
                 steps: ["Shake everything very hard with ice.", "Double-strain into a chilled glass for the foam."],
                 glass: "Coupe or martini glass", garnish: "Three coffee beans",
                 orderTip: "Smoke and coffee are a natural match after dinner."),
        Cocktail("mezcal-gimlet", "Mezcal Gimlet", base: .mezcal, style: .sour, strength: .medium,
                 blurb: "Mezcal and lime, sharp, smoky and simple.",
                 ingredients: [I("2", "mezcal"), I("¾", "fresh lime juice"), I("¾", "simple syrup")],
                 steps: shakeSour, glass: "Coupe", garnish: "Lime wheel",
                 orderTip: "Ask for agave syrup instead of simple for a rounder finish."),
        Cocktail("mezcal-tonic", "Mezcal Tonic", aliases: ["mezcal and tonic"], base: .mezcal, style: .highball, strength: .light,
                 blurb: "Mezcal and tonic over ice: a smoky G&T.",
                 ingredients: [I("1½", "mezcal"), I("4", "tonic water")],
                 steps: build, glass: "Highball or copa glass", garnish: "Grapefruit or orange slice",
                 orderTip: "Light, bitter and refreshing; great with a citrus wheel."),
        Cocktail("mezcal-hot-toddy", "Mezcal Hot Toddy", base: .mezcal, style: .hot, strength: .medium,
                 blurb: "Mezcal, honey, lemon and hot water. Smoky and soothing.",
                 ingredients: [I("1½", "mezcal"), I("½", "honey"), I("½", "fresh lemon juice"), I("4", "hot water")],
                 steps: ["Warm the mug with hot water, then empty it.", "Add honey and lemon, then the hot water; stir to dissolve.", "Add the mezcal and stir."],
                 glass: "Mug", garnish: "Lemon wheel and cinnamon stick",
                 orderTip: "A cozy nightcap with a campfire edge."),
        Cocktail("mezcal-spritz", "Mezcal Spritz", base: .mezcal, style: .spritz, strength: .light,
                 blurb: "Mezcal, Aperol and prosecco with soda: a smoky Aperol Spritz.",
                 ingredients: [I("1", "mezcal"), I("1", "Aperol"), I("3", "prosecco"), I("1", "club soda")],
                 steps: ["Fill a wine glass with ice.", "Add mezcal and Aperol, then prosecco and soda.", "Stir once."],
                 glass: "Wine glass", garnish: "Orange slice",
                 orderTip: "A good afternoon drink if a straight Aperol Spritz feels too sweet."),
        Cocktail("mezcal-penicillin", "Mezcal Penicillin", base: .mezcal, style: .sour, strength: .medium,
                 blurb: "The Penicillin with mezcal: honey, ginger, lemon and smoke.",
                 ingredients: [I("2", "mezcal"), I("¾", "honey-ginger syrup"), I("¾", "fresh lemon juice")],
                 steps: shakeSour, glass: "Rocks glass over ice", garnish: "Candied ginger",
                 orderTip: "Spicy, smoky and warming, like the Scotch original."),
        Cocktail("mezcal-ranch-water", "Mezcal Ranch Water", base: .mezcal, style: .fizzy, strength: .light,
                 blurb: "Mezcal, lime and Topo Chico. Ranch Water with smoke.",
                 ingredients: [I("1½", "mezcal"), I("½", "fresh lime juice"), I("", "Topo Chico (or sparkling water) to top")],
                 steps: build, glass: "Highball glass", garnish: "Lime wedge",
                 orderTip: "Low-sugar, bubbly and easy on a hot day."),
        Cocktail("mezcal-bloody-mary", "Mezcal Bloody Mary", base: .mezcal, style: .highball, strength: .light,
                 blurb: "A Bloody Mary with smoky mezcal instead of vodka.",
                 ingredients: [I("1½", "mezcal"), I("4", "tomato juice"), I("½", "fresh lime juice"), I("", "Worcestershire, hot sauce, celery salt and pepper to taste")],
                 steps: ["Add everything to a glass with ice.", "Roll between two tins (or stir) to mix.", "Garnish generously."],
                 glass: "Pint or highball glass", garnish: "Celery stalk, lime wedge, chili-salt rim",
                 orderTip: "The smoke makes it taste like it came off the grill."),
    ]
}
