import Foundation

// Make Me a Drink: more vodka drinks, so the Vodka chip has 20+ to surprise with.
extension CocktailLibrary {
    static let moreVodka: [Cocktail] = [
        Cocktail("vodka-gimlet", "Vodka Gimlet", base: .vodka, style: .sour, strength: .medium,
                 blurb: "Vodka and lime, clean and tart.",
                 ingredients: [I("2", "vodka"), I("¾", "fresh lime juice"), I("¾", "simple syrup")],
                 steps: shakeSour, glass: "Coupe", garnish: "Lime wheel",
                 orderTip: "Ask for fresh lime rather than lime cordial for a brighter drink."),
        Cocktail("black-russian", "Black Russian", base: .vodka, style: .stirred, strength: .strong,
                 blurb: "Vodka and coffee liqueur over ice: dark, smooth and simple.",
                 ingredients: [I("2", "vodka"), I("¾", "coffee liqueur")],
                 steps: ["Fill the glass with ice.", "Add the vodka and coffee liqueur.", "Stir until chilled."],
                 glass: "Rocks glass", garnish: "None",
                 orderTip: "Add a float of cream and it becomes a White Russian."),
        Cocktail("screwdriver", "Screwdriver", base: .vodka, style: .highball, strength: .light,
                 blurb: "Vodka and orange juice. Easy brunch sunshine.",
                 ingredients: [I("1½", "vodka"), I("4", "fresh orange juice")],
                 steps: build, glass: "Highball glass", garnish: "Orange slice",
                 orderTip: "Ask for fresh-squeezed juice if they have it."),
        Cocktail("greyhound", "Greyhound", base: .vodka, style: .highball, strength: .light,
                 blurb: "Vodka and grapefruit juice, crisp and a little bitter.",
                 ingredients: [I("1½", "vodka"), I("4", "fresh grapefruit juice")],
                 steps: build, glass: "Highball glass", garnish: "Grapefruit wedge",
                 orderTip: "Ask for a salted rim and it's a Salty Dog."),
        Cocktail("cape-codder", "Cape Codder", aliases: ["vodka cranberry", "cape cod"], base: .vodka, style: .highball, strength: .light,
                 blurb: "Vodka, cranberry and a squeeze of lime.",
                 ingredients: [I("1½", "vodka"), I("4", "cranberry juice"), I("", "squeeze of lime")],
                 steps: build, glass: "Highball glass", garnish: "Lime wedge",
                 orderTip: "Most bars just call it a vodka cranberry."),
        Cocktail("kamikaze", "Kamikaze", base: .vodka, style: .shot, strength: .medium,
                 blurb: "Equal parts vodka, triple sec and lime: a tart, zippy shot.",
                 ingredients: [I("½", "vodka"), I("½", "triple sec"), I("½", "fresh lime juice")],
                 steps: ["Shake everything with ice.", "Strain into a shot glass."],
                 glass: "Shot glass", garnish: "Lime wedge",
                 orderTip: "Order a round, or ask for it up in a coupe as a full drink."),
        Cocktail("harvey-wallbanger", "Harvey Wallbanger", base: .vodka, style: .highball, strength: .light,
                 blurb: "A screwdriver with a float of vanilla-herbal Galliano.",
                 ingredients: [I("1½", "vodka"), I("3", "fresh orange juice"), I("½", "Galliano")],
                 steps: ["Build the vodka and orange juice over ice.", "Stir, then float the Galliano on top."],
                 glass: "Highball glass", garnish: "Orange slice and cherry",
                 orderTip: "A 1970s favorite; the bar needs a bottle of Galliano."),
        Cocktail("french-martini", "French Martini", base: .vodka, style: .sour, strength: .medium,
                 blurb: "Vodka, raspberry liqueur and pineapple, shaken to a frothy top.",
                 ingredients: [I("1½", "vodka"), I("½", "Chambord (black raspberry liqueur)"), I("1½", "pineapple juice")],
                 steps: ["Shake everything very hard with ice.", "Strain into a chilled glass so the pineapple foams."],
                 glass: "Martini glass or coupe", garnish: "Lemon twist or raspberry",
                 orderTip: "Fruity and silky; a 1980s New York favorite."),
        Cocktail("sex-on-the-beach", "Sex on the Beach", base: .vodka, style: .highball, strength: .light,
                 blurb: "Vodka, peach schnapps, orange and cranberry. Fruity and fun.",
                 ingredients: [I("1½", "vodka"), I("½", "peach schnapps"), I("1½", "orange juice"), I("1½", "cranberry juice")],
                 steps: build, glass: "Highball glass", garnish: "Orange slice",
                 orderTip: "A sweet, easygoing beach-bar order."),
        Cocktail("pornstar-martini", "Pornstar Martini", aliases: ["passion fruit martini"], base: .vodka, style: .sour, strength: .medium,
                 blurb: "Vanilla vodka and passion fruit with a prosecco chaser.",
                 ingredients: [I("1½", "vanilla vodka"), I("½", "passion fruit liqueur"), I("½", "fresh lime juice"), I("½", "vanilla syrup"), I("2", "prosecco, served on the side")],
                 steps: ["Shake everything but the prosecco hard with ice.", "Double-strain into a chilled coupe.", "Serve the prosecco in a shot glass on the side."],
                 glass: "Coupe", garnish: "Half a passion fruit",
                 orderTip: "Sip the prosecco between sips, or pour it in."),
        Cocktail("caipiroska", "Caipiroska", base: .vodka, style: .sour, strength: .medium,
                 blurb: "A caipirinha made with vodka: muddled lime and sugar over crushed ice.",
                 ingredients: [I("2", "vodka"), I("½", "lime, cut into wedges"), I("2 tsp", "sugar")],
                 steps: ["Muddle the lime and sugar in the glass.", "Fill with crushed ice and add the vodka.", "Stir well."],
                 glass: "Rocks glass", garnish: "Lime wedge",
                 orderTip: "Try it with muddled strawberries or passion fruit."),
    ]
}
