import Foundation

// Make Me a Drink: more tequila drinks, so the Tequila chip has 20+ to surprise with.
extension CocktailLibrary {
    static let moreTequila: [Cocktail] = [
        Cocktail("tommys-margarita", "Tommy's Margarita", base: .tequila, style: .sour, strength: .medium,
                 blurb: "Tequila, lime and agave: a margarita with no orange liqueur, all agave.",
                 ingredients: [I("2", "blanco tequila"), I("1", "fresh lime juice"), I("½", "agave syrup")],
                 steps: shakeSour, glass: "Rocks glass over ice", garnish: "Lime wheel",
                 orderTip: "Ask for it with a good 100% agave tequila."),
        Cocktail("frozen-margarita", "Frozen Margarita", base: .tequila, style: .frozen, strength: .medium,
                 blurb: "The margarita blended with ice into a slushy, salty-rimmed treat.",
                 ingredients: [I("2", "blanco tequila"), I("1", "Cointreau"), I("1", "fresh lime juice"), I("½", "agave syrup")],
                 steps: ["Salt the rim of the glass.", "Blend everything with a cup of ice until smooth.", "Pour into the glass."],
                 glass: "Margarita glass", garnish: "Lime wheel, salt rim",
                 orderTip: "Ask for a fruit swirl (strawberry or mango) if they offer one."),
        Cocktail("cadillac-margarita", "Cadillac Margarita", base: .tequila, style: .sour, strength: .medium,
                 blurb: "A top-shelf margarita with reposado tequila and Grand Marnier.",
                 ingredients: [I("2", "reposado tequila"), I("¾", "Grand Marnier"), I("1", "fresh lime juice"), I("¼", "agave syrup")],
                 steps: ["Salt half the rim.", "Shake everything with ice.", "Strain over fresh ice."],
                 glass: "Rocks glass", garnish: "Lime wheel, salt rim",
                 orderTip: "Some bars float the Grand Marnier on top; either way is right."),
        Cocktail("el-diablo", "El Diablo", base: .tequila, style: .highball, strength: .light,
                 blurb: "Tequila, blackcurrant, lime and spicy ginger beer.",
                 ingredients: [I("1½", "reposado tequila"), I("½", "crème de cassis"), I("½", "fresh lime juice"), I("3", "ginger beer")],
                 steps: ["Shake the tequila, cassis and lime with ice.", "Strain into an ice-filled glass.", "Top with ginger beer."],
                 glass: "Highball glass", garnish: "Lime wedge",
                 orderTip: "A great pick if you like Moscow Mules."),
        Cocktail("matador", "Matador", base: .tequila, style: .sour, strength: .light,
                 blurb: "Tequila, pineapple and lime, bright and tropical.",
                 ingredients: [I("1½", "blanco tequila"), I("3", "pineapple juice"), I("½", "fresh lime juice")],
                 steps: shakeSour, glass: "Coupe or rocks glass over ice", garnish: "Pineapple wedge",
                 orderTip: "Fruity and easygoing; good for a first tequila cocktail."),
        Cocktail("siesta", "Siesta", base: .tequila, style: .sour, strength: .medium,
                 blurb: "Tequila, Campari, grapefruit and lime: a bittersweet daiquiri cousin.",
                 ingredients: [I("1½", "blanco tequila"), I("½", "Campari"), I("½", "fresh lime juice"), I("½", "fresh grapefruit juice"), I("½", "simple syrup")],
                 steps: shakeSour, glass: "Coupe", garnish: "Grapefruit twist",
                 orderTip: "Ideal if you love a Paloma and a Negroni."),
        Cocktail("batanga", "Batanga", base: .tequila, style: .highball, strength: .light,
                 blurb: "Tequila, lime and Mexican Coca-Cola in a salted glass.",
                 ingredients: [I("2", "blanco tequila"), I("½", "fresh lime juice"), I("4", "Mexican Coca-Cola"), I("", "pinch of salt for the rim")],
                 steps: ["Salt the rim and fill the glass with ice.", "Add tequila and lime, then top with cola.", "Stir (traditionally with a knife)."],
                 glass: "Highball glass with salt rim", garnish: "Lime wedge",
                 orderTip: "Ask for Mexican Coke made with cane sugar."),
        Cocktail("brave-bull", "Brave Bull", base: .tequila, style: .stirred, strength: .strong,
                 blurb: "Tequila and coffee liqueur over ice. Simple and strong.",
                 ingredients: [I("1½", "blanco tequila"), I("1", "coffee liqueur")],
                 steps: ["Fill the glass with ice.", "Add tequila and coffee liqueur.", "Stir until cold."],
                 glass: "Rocks glass", garnish: "Lemon twist (optional)",
                 orderTip: "Add cream and it becomes a Toro Bravo, a tequila White Russian."),
        Cocktail("rosita", "Rosita", base: .tequila, style: .stirred, strength: .strong,
                 blurb: "Reposado tequila, Campari and two vermouths, like a tequila Negroni.",
                 ingredients: [I("1½", "reposado tequila"), I("½", "Campari"), I("½", "sweet vermouth"), I("½", "dry vermouth"), I("1 dash", "Angostura bitters")],
                 steps: ["Stir everything with ice.", "Strain over a big ice cube."],
                 glass: "Rocks glass", garnish: "Lemon twist",
                 orderTip: "A softer, more agave-forward take on the Negroni."),
        Cocktail("cantarito", "Cantarito", base: .tequila, style: .fizzy, strength: .light,
                 blurb: "Tequila with fresh citrus and grapefruit soda, served in a clay cup.",
                 ingredients: [I("2", "blanco tequila"), I("1", "fresh orange juice"), I("1", "fresh grapefruit juice"), I("½", "fresh lime juice"), I("", "grapefruit soda to top"), I("", "pinch of salt")],
                 steps: ["Fill the cup with ice and add the tequila, juices and salt.", "Top with grapefruit soda.", "Stir gently."],
                 glass: "Clay cantarito cup or highball", garnish: "Citrus wedges, chili-salt rim",
                 orderTip: "A street-fair favorite from Jalisco; perfect on a hot day."),
        Cocktail("toreador", "Toreador", base: .tequila, style: .sour, strength: .medium,
                 blurb: "Tequila, apricot brandy and lime, served up.",
                 ingredients: [I("1½", "blanco tequila"), I("¾", "apricot brandy"), I("¾", "fresh lime juice")],
                 steps: shakeSour, glass: "Coupe", garnish: "Lime twist",
                 orderTip: "A vintage pick that's like a margarita with stone fruit."),
        Cocktail("juan-collins", "Juan Collins", aliases: ["tequila collins"], base: .tequila, style: .fizzy, strength: .light,
                 blurb: "A Tom Collins made with tequila: lemony, tall and bubbly.",
                 ingredients: [I("2", "blanco tequila"), I("1", "fresh lemon juice"), I("¾", "simple syrup"), I("2", "club soda")],
                 steps: ["Shake tequila, lemon and syrup with ice.", "Strain into an ice-filled glass.", "Top with soda."],
                 glass: "Collins glass", garnish: "Lemon wheel and cherry",
                 orderTip: "Ask for a Tequila Collins if they don't know the name."),
        Cocktail("bloody-maria", "Bloody Maria", base: .tequila, style: .highball, strength: .light,
                 blurb: "A Bloody Mary with tequila in place of vodka.",
                 ingredients: [I("1½", "blanco tequila"), I("4", "tomato juice"), I("½", "fresh lime juice"), I("", "Worcestershire, hot sauce, celery salt and pepper to taste")],
                 steps: ["Add everything to a glass with ice.", "Roll between two tins (or stir) to mix.", "Garnish generously."],
                 glass: "Pint or highball glass", garnish: "Celery stalk, lime wedge, jalapeño",
                 orderTip: "Ask for a Tajín rim for extra kick."),
        Cocktail("bandera", "Bandera", base: .tequila, style: .shot, strength: .medium,
                 blurb: "Three shots in the colors of the Mexican flag: lime, tequila and sangrita.",
                 ingredients: [I("1½", "fresh lime juice"), I("1½", "blanco tequila"), I("1½", "sangrita")],
                 steps: ["Pour each into its own shot glass, in a row.", "Sip the lime, then the tequila, then the sangrita.", "Repeat in order until done."],
                 glass: "Three shot glasses", garnish: "None",
                 orderTip: "Sip, don't slam: it's meant to be savored."),
    ]
}
