import Foundation

// Make Me a Drink: more brandy drinks (Cognac, pisco, applejack and Calvados),
// so the Brandy chip has 20+ to surprise with.
extension CocktailLibrary {
    static let moreBrandy: [Cocktail] = [
        Cocktail("pisco-sour", "Pisco Sour", base: .brandy, style: .sour, strength: .medium,
                 blurb: "Pisco, lime and sugar under a silky egg-white foam.",
                 ingredients: [I("2", "pisco"), I("1", "fresh lime juice"), I("¾", "simple syrup"), I("1", "egg white"), I("3 drops", "Angostura bitters")],
                 steps: ["Shake pisco, lime, syrup and egg white without ice.", "Add ice and shake hard.", "Strain into the glass and dot the foam with bitters."],
                 glass: "Coupe or sour glass", garnish: "Angostura drops",
                 orderTip: "Peru and Chile both claim it; either way, order it at a Peruvian spot."),
        Cocktail("pisco-punch", "Pisco Punch", base: .brandy, style: .sour, strength: .medium,
                 blurb: "Pisco, pineapple syrup and lemon from Gold Rush-era San Francisco.",
                 ingredients: [I("2", "pisco"), I("1", "pineapple syrup (or gum syrup)"), I("¾", "fresh lemon juice")],
                 steps: shakeSour, glass: "Rocks glass over ice", garnish: "Pineapple wedge",
                 orderTip: "Fruity and dangerously easy to drink."),
        Cocktail("chilcano", "Chilcano", base: .brandy, style: .highball, strength: .light,
                 blurb: "Pisco, lime and ginger ale with a few dashes of bitters.",
                 ingredients: [I("2", "pisco"), I("½", "fresh lime juice"), I("4", "ginger ale"), I("3 dashes", "Angostura bitters")],
                 steps: ["Fill the glass with ice.", "Add pisco and lime, then top with ginger ale.", "Dash bitters on top and stir gently."],
                 glass: "Highball glass", garnish: "Lime wheel",
                 orderTip: "Peru's favorite highball, lighter than a Pisco Sour."),
        Cocktail("jack-rose", "Jack Rose", base: .brandy, style: .sour, strength: .medium,
                 blurb: "Applejack, grenadine and citrus: rosy pink and apple-crisp.",
                 ingredients: [I("2", "applejack or Calvados"), I("¾", "fresh lemon juice"), I("½", "grenadine")],
                 steps: shakeSour, glass: "Coupe", garnish: "Apple slice or lemon twist",
                 orderTip: "Best with real pomegranate grenadine; ask if they make their own."),
        Cocktail("stinger", "Stinger", base: .brandy, style: .stirred, strength: .strong,
                 blurb: "Cognac and white crème de menthe: a cool, minty nightcap.",
                 ingredients: [I("2", "Cognac"), I("¾", "white crème de menthe")],
                 steps: stir, glass: "Coupe or rocks glass over crushed ice", garnish: "Mint sprig",
                 orderTip: "An old-school after-dinner drink; ask for it over crushed ice."),
        Cocktail("between-the-sheets", "Between the Sheets", base: .brandy, style: .sour, strength: .strong,
                 blurb: "Cognac, light rum, orange liqueur and lemon. A boozy Sidecar.",
                 ingredients: [I("1", "Cognac"), I("1", "white rum"), I("1", "triple sec"), I("¾", "fresh lemon juice")],
                 steps: shakeSour, glass: "Coupe", garnish: "Orange twist",
                 orderTip: "Love a Sidecar? This is its stronger cousin."),
        Cocktail("brandy-crusta", "Brandy Crusta", base: .brandy, style: .sour, strength: .strong,
                 blurb: "Cognac, curaçao, maraschino and lemon in a sugar-crusted glass.",
                 ingredients: [I("1¾", "Cognac"), I("1 tsp", "orange curaçao"), I("¼", "maraschino liqueur"), I("½", "fresh lemon juice"), I("¼", "simple syrup"), I("2 dashes", "Angostura bitters")],
                 steps: ["Sugar the rim and line the glass with a long lemon peel.", "Shake everything with ice.", "Strain into the glass."],
                 glass: "Small wine glass with sugar rim", garnish: "Long lemon peel",
                 orderTip: "The 1850s New Orleans ancestor of the Sidecar."),
        Cocktail("corpse-reviver-no-1", "Corpse Reviver No. 1", base: .brandy, style: .stirred, strength: .strong,
                 blurb: "Cognac, Calvados and sweet vermouth, rich and warming.",
                 ingredients: [I("1½", "Cognac"), I("¾", "Calvados or applejack"), I("¾", "sweet vermouth")],
                 steps: stir, glass: "Coupe", garnish: "Orange twist",
                 orderTip: "Not the gin No. 2; this one is the darker, brandy original."),
        Cocktail("metropolitan", "Metropolitan", base: .brandy, style: .stirred, strength: .strong,
                 blurb: "A brandy Manhattan: Cognac, sweet vermouth and bitters.",
                 ingredients: [I("1½", "Cognac"), I("1", "sweet vermouth"), I("½ tsp", "simple syrup"), I("2 dashes", "Angostura bitters")],
                 steps: stir, glass: "Coupe", garnish: "Lemon twist",
                 orderTip: "Order it if you like Manhattans but want something softer."),
        Cocktail("champs-elysees", "Champs-Élysées", aliases: ["champs elysees"], base: .brandy, style: .sour, strength: .medium,
                 blurb: "Cognac, green Chartreuse and lemon: herbal and bright.",
                 ingredients: [I("1½", "Cognac"), I("½", "green Chartreuse"), I("¾", "fresh lemon juice"), I("½", "simple syrup"), I("1 dash", "Angostura bitters")],
                 steps: shakeSour, glass: "Coupe", garnish: "Lemon twist",
                 orderTip: "A Parisian sour for Chartreuse fans."),
        Cocktail("japanese-cocktail", "Japanese Cocktail", base: .brandy, style: .stirred, strength: .strong,
                 blurb: "Cognac, almond orgeat and bitters. Short, nutty and smooth.",
                 ingredients: [I("2", "Cognac"), I("½", "orgeat"), I("2 dashes", "Angostura bitters")],
                 steps: stir, glass: "Coupe", garnish: "Lemon twist",
                 orderTip: "One of the oldest cocktails on record, from Jerry Thomas in 1862."),
        Cocktail("brandy-milk-punch", "Brandy Milk Punch", aliases: ["milk punch"], base: .brandy, style: .creamy, strength: .medium,
                 blurb: "Brandy, milk, sugar and vanilla, shaken cold with nutmeg on top.",
                 ingredients: [I("2", "brandy"), I("3", "whole milk or half-and-half"), I("¾", "simple syrup"), I("2 dashes", "vanilla extract")],
                 steps: ["Shake everything hard with ice.", "Strain into an ice-filled glass.", "Grate nutmeg on top."],
                 glass: "Highball or rocks glass", garnish: "Grated nutmeg",
                 orderTip: "A New Orleans brunch classic; Brennan's is famous for it."),
        Cocktail("brandy-old-fashioned", "Brandy Old Fashioned", aliases: ["wisconsin old fashioned"], base: .brandy, style: .stirred, strength: .medium,
                 blurb: "Wisconsin's favorite: brandy with muddled orange and cherry, topped with soda.",
                 ingredients: [I("2", "brandy"), I("1", "sugar cube"), I("3 dashes", "Angostura bitters"), I("1", "orange slice"), I("1", "maraschino cherry"), I("", "lemon-lime soda (sweet) or grapefruit soda (sour) to top")],
                 steps: ["Muddle the sugar, bitters, orange and cherry in the glass.", "Add ice and brandy.", "Top with soda and stir."],
                 glass: "Rocks glass", garnish: "Orange slice and cherry",
                 orderTip: "In Wisconsin, order it \"sweet\" or \"sour\" to pick the soda."),
        Cocktail("french-connection", "French Connection", base: .brandy, style: .stirred, strength: .strong,
                 blurb: "Cognac and amaretto over ice. Nutty, smooth and simple.",
                 ingredients: [I("1½", "Cognac"), I("1", "amaretto")],
                 steps: ["Fill the glass with ice.", "Add Cognac and amaretto.", "Stir until cold."],
                 glass: "Rocks glass", garnish: "None",
                 orderTip: "A two-ingredient nightcap any bar can make."),
        Cocktail("harvard", "Harvard", base: .brandy, style: .stirred, strength: .medium,
                 blurb: "Cognac and sweet vermouth with bitters and a splash of soda.",
                 ingredients: [I("1½", "Cognac"), I("¾", "sweet vermouth"), I("1 tsp", "simple syrup"), I("2 dashes", "Angostura bitters"), I("1", "club soda")],
                 steps: ["Stir the Cognac, vermouth, syrup and bitters with ice.", "Strain into the chilled glass.", "Top with a splash of soda."],
                 glass: "Coupe", garnish: "Lemon twist",
                 orderTip: "A lighter, livelier brandy Manhattan."),
        Cocktail("brandy-smash", "Brandy Smash", base: .brandy, style: .highball, strength: .medium,
                 blurb: "Cognac, mint and lemon over crushed ice.",
                 ingredients: [I("2", "Cognac"), I("¾", "simple syrup"), I("3", "lemon wedges"), I("6", "mint leaves")],
                 steps: ["Muddle the lemon wedges and mint with the syrup.", "Add Cognac and shake with ice.", "Strain over crushed ice."],
                 glass: "Rocks glass", garnish: "Mint sprig",
                 orderTip: "Like a Mint Julep with brandy and a squeeze of lemon."),
        Cocktail("tom-and-jerry", "Tom and Jerry", base: .brandy, style: .hot, strength: .medium,
                 blurb: "Brandy and rum in hot milk with a sweet, spiced egg batter.",
                 ingredients: [I("1", "brandy"), I("1", "dark rum"), I("2 tbsp", "Tom and Jerry batter (eggs, sugar, spices)"), I("4", "hot milk")],
                 steps: ["Spoon the batter into a warmed mug.", "Add brandy and rum, then stir in the hot milk.", "Grate nutmeg on top."],
                 glass: "Mug", garnish: "Grated nutmeg",
                 orderTip: "A Midwest holiday tradition; look for it around Christmas."),
    ]
}
