import Foundation

// Make Me a Drink: more rum drinks, so the Rum chip has 20+ to surprise with.
extension CocktailLibrary {
    static let moreRum: [Cocktail] = [
        Cocktail("hemingway-daiquiri", "Hemingway Daiquiri", aliases: ["papa doble"], base: .rum, style: .sour, strength: .medium,
                 blurb: "A dry daiquiri with grapefruit and maraschino.",
                 ingredients: [I("2", "white rum"), I("¾", "fresh lime juice"), I("½", "fresh grapefruit juice"), I("½", "maraschino liqueur")],
                 steps: shakeSour, glass: "Coupe", garnish: "Lime wheel",
                 orderTip: "Tart and not very sweet, the way Papa liked it."),
        Cocktail("strawberry-daiquiri", "Strawberry Daiquiri", base: .rum, style: .frozen, strength: .light,
                 blurb: "Rum, lime and ripe strawberries, blended icy and pink.",
                 ingredients: [I("2", "white rum"), I("1", "fresh lime juice"), I("¾", "simple syrup"), I("5", "fresh strawberries, hulled")],
                 steps: ["Blend everything with a cup of ice until smooth.", "Pour into the glass."],
                 glass: "Hurricane or coupe glass", garnish: "Strawberry",
                 orderTip: "Ask if they use fresh fruit rather than a premade mix."),
        Cocktail("zombie", "Zombie", base: .rum, style: .tiki, strength: .strong,
                 blurb: "Three rums, lime, grapefruit, cinnamon and falernum. Famously potent.",
                 ingredients: [I("1½", "gold Puerto Rican rum"), I("1½", "gold Jamaican rum"), I("1", "151-proof Demerara rum"), I("¾", "fresh lime juice"), I("½", "Don's Mix (2 parts grapefruit juice, 1 part cinnamon syrup)"), I("½", "falernum"), I("1 tsp", "grenadine"), I("1 dash", "Angostura bitters"), I("6 drops", "absinthe or Pernod")],
                 steps: ["Add everything to a blender with ¾ cup of crushed ice.", "Flash-blend for about 5 seconds.", "Pour into a tall glass and top with more ice."],
                 glass: "Zombie or tiki glass", garnish: "Mint sprig",
                 orderTip: "Many tiki bars limit you to two. Take the hint."),
        Cocktail("jungle-bird", "Jungle Bird", base: .rum, style: .tiki, strength: .medium,
                 blurb: "Dark rum, Campari, pineapple and lime: bittersweet tiki.",
                 ingredients: [I("1½", "blackstrap or dark rum"), I("¾", "Campari"), I("1½", "pineapple juice"), I("½", "fresh lime juice"), I("½", "demerara syrup")],
                 steps: ["Shake everything with ice.", "Strain over fresh ice."],
                 glass: "Rocks glass", garnish: "Pineapple wedge",
                 orderTip: "Perfect if you love Negronis and beaches."),
        Cocktail("cuba-libre", "Cuba Libre", aliases: ["rum and coke"], base: .rum, style: .highball, strength: .light,
                 blurb: "Rum and cola brightened with fresh lime.",
                 ingredients: [I("2", "white rum"), I("4", "cola"), I("½", "fresh lime juice")],
                 steps: build, glass: "Highball glass", garnish: "Lime wedge",
                 orderTip: "Ask for extra lime; that's what makes it a Cuba Libre."),
        Cocktail("el-presidente", "El Presidente", base: .rum, style: .stirred, strength: .strong,
                 blurb: "Havana's elegant stirred rum drink with vermouth and curaçao.",
                 ingredients: [I("1½", "white rum"), I("¾", "blanc vermouth"), I("¼", "orange curaçao"), I("1 tsp", "grenadine")],
                 steps: stir, glass: "Coupe", garnish: "Orange peel",
                 orderTip: "A rum Manhattan of sorts, for rum lovers who sip."),
        Cocktail("hot-buttered-rum", "Hot Buttered Rum", base: .rum, style: .hot, strength: .medium,
                 blurb: "Dark rum with spiced butter and brown sugar, topped with hot water.",
                 ingredients: [I("2", "dark or aged rum"), I("1 tbsp", "spiced butter batter (butter, brown sugar, cinnamon, nutmeg, clove)"), I("4", "hot water")],
                 steps: ["Warm the mug with hot water, then empty it.", "Add the butter batter and rum.", "Top with hot water and stir until melted."],
                 glass: "Mug", garnish: "Cinnamon stick and grated nutmeg",
                 orderTip: "A winter treat; bars that make it usually have batter ready."),
        Cocktail("planters-punch", "Planter's Punch", base: .rum, style: .tiki, strength: .medium,
                 blurb: "Jamaican rum, citrus and pineapple with a splash of grenadine.",
                 ingredients: [I("1½", "dark Jamaican rum"), I("1", "fresh orange juice"), I("1", "pineapple juice"), I("¾", "fresh lemon juice"), I("¼", "grenadine"), I("¼", "simple syrup"), I("3 dashes", "Angostura bitters")],
                 steps: ["Shake everything with ice.", "Strain into an ice-filled glass."],
                 glass: "Collins glass", garnish: "Orange slice, cherry and mint",
                 orderTip: "The original rum punch; fruity but rum-forward."),
        Cocktail("air-mail", "Air Mail", base: .rum, style: .fizzy, strength: .medium,
                 blurb: "Gold rum, lime and honey topped with Champagne.",
                 ingredients: [I("1½", "gold rum"), I("½", "fresh lime juice"), I("½", "honey syrup"), I("2", "Champagne or brut sparkling wine")],
                 steps: ["Shake the rum, lime and honey syrup with ice.", "Strain into the glass.", "Top with Champagne."],
                 glass: "Champagne flute or coupe", garnish: "Lime wheel",
                 orderTip: "Like a French 75 made with rum and honey."),
        Cocktail("mary-pickford", "Mary Pickford", base: .rum, style: .sour, strength: .medium,
                 blurb: "White rum, pineapple, maraschino and a touch of grenadine.",
                 ingredients: [I("1½", "white rum"), I("1½", "pineapple juice"), I("1 tsp", "maraschino liqueur"), I("1 tsp", "grenadine")],
                 steps: shakeSour, glass: "Coupe", garnish: "Brandied cherry",
                 orderTip: "Soft, fruity and pink, a 1920s Havana classic."),
        Cocktail("queens-park-swizzle", "Queen's Park Swizzle", base: .rum, style: .tiki, strength: .strong,
                 blurb: "Demerara rum, lime and mint swizzled over crushed ice with a bitters top.",
                 ingredients: [I("2", "Demerara rum"), I("¾", "fresh lime juice"), I("½", "demerara syrup"), I("8", "mint leaves"), I("4 dashes", "Angostura bitters")],
                 steps: ["Lightly press the mint with the syrup in the glass.", "Add the rum and lime and fill with crushed ice.", "Swizzle until the glass frosts, then dash the bitters on top."],
                 glass: "Collins glass", garnish: "Mint sprig",
                 orderTip: "A mojito's bolder Trinidad cousin."),
        Cocktail("bushwacker", "Bushwacker", base: .rum, style: .creamy, strength: .medium,
                 blurb: "Dark rum, coffee liqueur, chocolate and coconut, blended like a milkshake.",
                 ingredients: [I("1", "dark rum"), I("1", "coffee liqueur"), I("1", "dark crème de cacao"), I("2", "cream of coconut"), I("2", "whole milk")],
                 steps: ["Blend everything with a cup of ice until smooth.", "Pour into the glass."],
                 glass: "Hurricane glass", garnish: "Grated nutmeg",
                 orderTip: "A Gulf Coast beach-bar favorite; ask for a dark rum float on top."),
    ]
}
