import Foundation

// Make Me a Drink: more wine and bubbly drinks, so the Wine & Bubbly chip has 20+ to surprise with.
extension CocktailLibrary {
    static let moreBubbly: [Cocktail] = [
        Cocktail("champagne-cocktail", "Champagne Cocktail", base: .bubbly, style: .fizzy, strength: .light,
                 blurb: "A bitters-soaked sugar cube fizzing away in a flute of Champagne.",
                 ingredients: [I("1", "sugar cube"), I("2 dashes", "Angostura bitters"), I("5", "Champagne")],
                 steps: ["Drop the sugar cube into a flute and soak it with the bitters.", "Top slowly with chilled Champagne."],
                 glass: "Champagne flute", garnish: "Lemon twist",
                 orderTip: "A timeless toast; watch the bubbles stream off the sugar."),
        Cocktail("bamboo", "Bamboo", base: .bubbly, style: .stirred, strength: .light,
                 blurb: "Dry sherry and dry vermouth: a crisp, low-proof Martini cousin.",
                 ingredients: [I("1½", "fino or amontillado sherry"), I("1½", "dry vermouth"), I("2 dashes", "orange bitters"), I("1 dash", "Angostura bitters")],
                 steps: stir, glass: "Coupe or Nick & Nora", garnish: "Lemon twist",
                 orderTip: "A great aperitif when you want something stirred but gentle."),
        Cocktail("adonis", "Adonis", base: .bubbly, style: .stirred, strength: .light,
                 blurb: "Fino sherry and sweet vermouth, nutty and softly sweet.",
                 ingredients: [I("1½", "fino sherry"), I("1½", "sweet vermouth"), I("2 dashes", "orange bitters")],
                 steps: stir, glass: "Coupe", garnish: "Orange twist",
                 orderTip: "Like a Manhattan made with sherry instead of whiskey."),
        Cocktail("kalimotxo", "Kalimotxo", aliases: ["calimocho"], base: .bubbly, style: .highball, strength: .light,
                 blurb: "Red wine and cola over ice, a Basque party favorite.",
                 ingredients: [I("4", "dry red wine"), I("4", "cola")],
                 steps: build, glass: "Highball glass", garnish: "Lemon wedge",
                 orderTip: "Use an inexpensive young red; this is not the place for the good bottle."),
        Cocktail("tinto-de-verano", "Tinto de Verano", base: .bubbly, style: .highball, strength: .light,
                 blurb: "Red wine and lemon soda: Spain's easy summer red.",
                 ingredients: [I("4", "young red wine"), I("4", "lemon soda (or lemon-lime soda)")],
                 steps: build, glass: "Highball or tumbler", garnish: "Lemon slice",
                 orderTip: "In Spain it's what locals drink instead of sangria."),
        Cocktail("white-wine-spritzer", "White Wine Spritzer", aliases: ["spritzer", "wine spritzer"], base: .bubbly, style: .spritz, strength: .light,
                 blurb: "Crisp white wine stretched with soda water.",
                 ingredients: [I("4", "dry white wine"), I("2", "club soda")],
                 steps: ["Fill a wine glass with ice.", "Add the wine, then top with soda.", "Stir once."],
                 glass: "Wine glass", garnish: "Lemon twist",
                 orderTip: "Ask for a Sauvignon Blanc or Pinot Grigio base."),
        Cocktail("rossini", "Rossini", base: .bubbly, style: .fizzy, strength: .light,
                 blurb: "Prosecco with fresh strawberry purée, the Bellini's berry sibling.",
                 ingredients: [I("2", "strawberry purée"), I("4", "prosecco")],
                 steps: ["Add the purée to a flute.", "Top slowly with prosecco and stir gently."],
                 glass: "Champagne flute", garnish: "Strawberry",
                 orderTip: "Perfect for brunch when strawberries are in season."),
        Cocktail("poinsettia", "Poinsettia", base: .bubbly, style: .fizzy, strength: .light,
                 blurb: "Cranberry, orange liqueur and Champagne, made for the holidays.",
                 ingredients: [I("½", "Cointreau or triple sec"), I("1", "cranberry juice"), I("4", "Champagne")],
                 steps: ["Add the Cointreau and cranberry to a flute.", "Top with Champagne."],
                 glass: "Champagne flute", garnish: "A few fresh cranberries",
                 orderTip: "A festive swap for a Mimosa at a holiday party."),
        Cocktail("mulled-wine", "Mulled Wine", aliases: ["glühwein", "gluhwein", "vin chaud"], base: .bubbly, style: .hot, strength: .light,
                 blurb: "Red wine warmed with orange, honey and winter spices.",
                 ingredients: [I("1 bottle", "red wine"), I("1", "orange, sliced"), I("¼ cup", "honey or sugar"), I("2", "cinnamon sticks"), I("4", "whole cloves"), I("2", "star anise"), I("2", "brandy (optional)")],
                 steps: ["Combine everything in a pot.", "Warm gently for 15 minutes without boiling.", "Ladle into mugs."],
                 glass: "Mug", garnish: "Orange slice and cinnamon stick",
                 orderTip: "A Christmas market classic; ask for it with a shot of brandy if you want more warmth."),
        Cocktail("sherry-cobbler", "Sherry Cobbler", base: .bubbly, style: .highball, strength: .light,
                 blurb: "Sherry, sugar and orange over crushed ice, piled with fruit.",
                 ingredients: [I("3", "amontillado sherry"), I("½", "simple syrup"), I("2", "orange slices")],
                 steps: ["Shake everything with ice to break up the orange.", "Strain over a glass packed with crushed ice.", "Pile on the fruit and add a straw."],
                 glass: "Collins glass or julep cup", garnish: "Orange slice, berries and mint",
                 orderTip: "A 19th-century hit that's light, nutty and very refreshing."),
        Cocktail("port-and-tonic", "Port & Tonic", aliases: ["portonic", "white port and tonic"], base: .bubbly, style: .highball, strength: .light,
                 blurb: "White port and tonic, Porto's answer to the G&T.",
                 ingredients: [I("2", "white port"), I("4", "tonic water")],
                 steps: build, glass: "Highball or copa glass", garnish: "Orange slice and mint",
                 orderTip: "Ask for dry white port so it isn't too sweet."),
        Cocktail("rebujito", "Rebujito", base: .bubbly, style: .highball, strength: .light,
                 blurb: "Dry sherry and lemon-lime soda, the drink of Seville's Feria.",
                 ingredients: [I("2", "manzanilla or fino sherry"), I("4", "lemon-lime soda")],
                 steps: build, glass: "Highball glass", garnish: "Mint sprig",
                 orderTip: "Very light and made for long sunny afternoons."),
        Cocktail("black-velvet", "Black Velvet", base: .bubbly, style: .fizzy, strength: .light,
                 blurb: "Stout layered with Champagne: silky, dark and a little toasty.",
                 ingredients: [I("3", "stout (Guinness)"), I("3", "Champagne")],
                 steps: ["Pour the Champagne into a flute.", "Slowly float the stout on top over the back of a spoon."],
                 glass: "Champagne flute", garnish: "None",
                 orderTip: "An unexpected pairing that works; good for St. Patrick's Day brunch."),
        Cocktail("bucks-fizz", "Buck's Fizz", base: .bubbly, style: .fizzy, strength: .light,
                 blurb: "Champagne with a splash of orange juice, heavier on the bubbles than a Mimosa.",
                 ingredients: [I("4", "Champagne"), I("2", "fresh orange juice")],
                 steps: ["Pour the orange juice into a flute.", "Top slowly with Champagne."],
                 glass: "Champagne flute", garnish: "Orange twist",
                 orderTip: "The British brunch classic; drier and fizzier than a Mimosa."),
        Cocktail("kir", "Kir", base: .bubbly, style: .stirred, strength: .light,
                 blurb: "Crisp white wine with a splash of blackcurrant liqueur.",
                 ingredients: [I("½", "crème de cassis"), I("4", "dry white wine (Aligoté is traditional)")],
                 steps: ["Add the cassis to a chilled wine glass.", "Top with cold white wine."],
                 glass: "Wine glass", garnish: "None",
                 orderTip: "The still-wine original; ask for a Kir Royale if you want bubbles."),
    ]
}
